RakambdaOrg/ChannelPointsMiner

- src/main/java/fr/raksrinana/channelpointsminer/irc/TwitchIrcClient.java
- src/test/java/fr/raksrinana/channelpointsminer/irc/TwitchIrcClientTest.java
If an IRC channel is already joined, do not join it back. Same when leaving a channel.
> Do not join already joined IRC channels

- .github/PULL_REQUEST_TEMPLATE.md
- gradle/libs.versions.toml
- miner/build.gradle.kts
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/database/BaseDatabase.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/database/IDatabase.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/database/MariaDBDatabase.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/database/NoOpDatabase.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/database/SQLiteDatabase.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/database/model/prediction/OutcomeStatistic.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/factory/MinerFactory.java
- miner/src/main/resources/db/migrations/sqlite/V1_0_0__base.sql
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/database/SQLiteDatabaseTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/factory/MinerFactoryTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/tests/WebsocketMockServerExtension.java
- miner/src/test/resources/log4j2-test.xml
- viewer/build.gradle.kts
> Add database tests

- .github/workflows/analyse.yml
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/MinerApplication.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLApi.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/data/IntegrityResponse.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/passport/exceptions/IntegrityError.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/util/json/MillisecondsTimestampDeserializer.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/discord/DiscordApiTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/AbstractGQLTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/CommonGQLTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLApiChannelPointsContextTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLApiChatRoomBanStatusTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLApiClaimCommunityMomentTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLApiClaimCommunityPointsTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLApiDropsHighlightServiceAvailableDropsTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLApiDropsPageClaimDropRewardsTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLApiInventoryTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLApiJoinRaidTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLApiMakePredictionTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLApiReportMenuItemTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLApiVideoPlayerStreamInfoOverlayChannelTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLChannelFollowsTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/passport/PassportApiTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/twitch/TwitchApiTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/tests/UnirestMock.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/tests/UnirestMockExtension.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/util/json/MillisecondsTimestampDeserializerTest.java
- miner/src/test/resources/api/gql/integrity_needRefresh.json
- miner/src/test/resources/api/gql/integrity_noToken.json
- miner/src/test/resources/api/gql/integrity_ok.json
> Add integrity token to GQL requests

- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLApi.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/event/impl/ClaimedMomentEvent.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/event/impl/DropClaimedEvent.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/factory/ApiFactory.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/handler/ClaimMomentHandler.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/runnable/SyncInventory.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/AbstractGQLTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/CommonGQLTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLChannelFollowsTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/handler/ClaimMomentHandlerTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/log/DiscordEventListenerEmbedTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/log/DiscordEventListenerMessageTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/runnable/SyncInventoryTest.java
> Fire events when moment/drop is actually claimed + get Client-Version value dynamically

- miner/docs/modules/ROOT/examples/global-config-cookies-schema.json
- miner/docs/modules/ROOT/examples/global-config-schema.json
- miner/docs/modules/ROOT/examples/streamer-config-schema.json
- miner/docs/modules/ROOT/pages/configuration/index.adoc
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/passport/browser/BrowserPassportApi.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/browser/BrowserController.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/browser/CookieData.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/config/login/BrowserConfiguration.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/miner/Miner.java
- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/util/json/CookieSameSiteDeserializer.java
- miner/src/schema/java/fr/raksrinana/channelpointsminer/miner/ConfigSchemaGenerator.java
- miner/src/schema/java/fr/raksrinana/channelpointsminer/miner/CookiesFileType.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/passport/browser/BrowserPassportApiTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/factory/ConfigurationFactoryTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/miner/MinerTest.java
- miner/src/test/java/fr/raksrinana/channelpointsminer/miner/util/json/CookieSameSiteDeserializerTest.java
- miner/src/test/resources/config/config-with-more-customization.json
> Ability to provide a cookies file for BROWSER login method

- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/browser/Browser.java
> Less chrome selenium logs

- miner/src/main/java/fr/raksrinana/channelpointsminer/miner/factory/ApiFactory.java
> Automatic Discord retry on HTTP 429 (rate limit)

- miner/build.gradle.kts
- miner/docs/modules/ROOT/pages/installation/clone.adoc
> Running miner from shadow jar sometimes produces errors about unsupported elements / unknown classes

- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/ws/data/message/IPubSubMessage.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/ws/data/message/ReadNotifications.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/ws/data/message/readnotifications/ReadNotificationsData.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/handler/ClaimMomentHandler.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/handler/PubSubMessageHandlerAdapter.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SyncInventory.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/ws/TwitchPubSubWebSocketClientMessageTest.java
- miner/src/test/resources/api/ws/readNotifications.json
> Parse "read-notifications" message

- .editorconfig
- miner/build.gradle.kts
- miner/docs/modules/ROOT/examples/global-config-schema.json
- miner/docs/modules/ROOT/examples/streamer-config-schema.json
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/config/AnalyticsConfiguration.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/database/DatabaseEventHandler.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/factory/DatabaseFactory.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/factory/MinerFactory.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/miner/Miner.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/database/DatabaseEventHandlerTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/factory/ConfigurationFactoryTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/factory/DatabaseFactoryTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/factory/MinerFactoryTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/miner/MinerTest.java
- miner/src/test/resources/config/config-with-more-customization.json
New Feature
Currently recordChatPredictions  only filters predictions from the chat. Instead recordUserPredictions  will fully enable/disable recording user predictions. This can avoid some load on the DB if this data isn't wanted.
> Rename recordChatPredictions to recordUserPredictions in analyrics

- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/Tag.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/priority/DropsPriority.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/streamer/Streamer.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/priority/DropsPriorityTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/streamer/StreamerTest.java
It isn't present on all channels that can have drops. Checking DropsHighlights should be enough.
Bug fix
CPM was expecting a "Drops" tag on the stream but it seems it isn't always present anymore.
> Fix: do not check for the "Drops" tag anymore

- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/twitch/data/MinuteWatchedProperties.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/ws/data/message/subtype/Summary.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/miner/Miner.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendMinutesWatched.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/util/json/UnknownDeserializer.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/twitch/TwitchApiTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/runnable/SendMinutesWatchedTest.java
Bug fix
Seems like Twitch changed the data needed to be sent to the server in order to make drops progress.
See: https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/pull/378
> Fix: Send more data to MinuteWatched to make drops progress & Unrecognized field "count_by_md"

- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApi.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/dropshighlightserviceavailabledrops/DropsHighlightServiceAvailableDropsOperation.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/DropCampaign.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/DropCampaignSummary.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/GQLType.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/priority/DropsPriority.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/streamer/Streamer.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/streamer/StreamerSettings.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/AbstractGQLTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApiDropsHighlightServiceAvailableDropsTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLChannelFollowsTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/priority/DropsPriorityTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/streamer/StreamerSettingsTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/streamer/StreamerTest.java
- miner/src/test/resources/api/gql/gql/dropsHighlightServiceAvailableDrops_withDrops.json
Thanks to @jabbink on Discord
Bug fix
New Feature
Some drops can now be restricted for subscribers, this adds an option to ignore or not those drops. By default subscriber drops will nbe ignored.
Also fix some drops being stuck trying to be claimed even though they already are.
> Add option to ignore subscriber drops & fix checking drop count

- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/twitch/TwitchApi.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/twitch/TwitchApiTest.java
Internal change
Using head request will prevent the body from being downloaded requiring less network IO
> Improve M3U8 request by performing head request

- miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendM3u8MinutesWatched.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendMinutesWatched.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendSpadeMinutesWatched.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/UpdateStreamInfo.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/streamer/Streamer.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/runnable/SendMinutesWatchedTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/runnable/UpdateStreamInfoTest.java
Bug fix
There are two issues with watch time tracking that result in missed WATCH_STREAK events:
1. Both SendMinutesWatched instances increase the watchtime despite one triggering 4 times a minute, and one once a minute, increasing watchtime by 5 minutes per minute. This change prevents the M3U8 tracker (4 times a minute) to increase watch time in the internal counter
2. Sometimes streamers go live for a minute, something breaks, they stop, and restart quickly. This would reset last offline immediately, preventing the next go-live to be seen as eligible for a WATCH_STREAK. This PR will only reset the last offline tracker if we have watched them for long enough.
> Fix incorrect watch time tracking

- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/UserDropReward.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/priority/DropsPriority.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApiInventoryTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/priority/DropsPriorityTest.java
Bug fix
Check last awarded time in inventory prior to dismissing drops based on the claim limit. Some publishers reuse the same BenefitEdge/Drop over and over again while being fungible drops in their respective games (e.g. Hearthstone card packs being all "the same" according to the drop settings on twitch, but offering different contents in the game itself)
> Drops: Re-used BenefitEdge may be of interest

- miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendM3u8MinutesWatched.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendMinutesWatched.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendSpadeMinutesWatched.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/streamer/Streamer.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/runnable/SendMinutesWatchedTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/streamer/StreamerTest.java
New feature and breaking change  
Nothing changes in configuration, but if a user wants to farm channel points specifically for channels with drops enabled, this will break their workflow. I don't think anyone would want to do that but you never know. To me it is more logical to just get drops, and then, if the priority is high enough based on other things, get channel points there as well, or on a totally different channel.
New logic:
- Watch highest priority drops enabled streamer via M3U8
- Watch two highest-priority, ignoring Drops, streamer via Spade
Can effectively "watch" 3 different streams, giving channel points on 2 according to ALL priority settings except for DropsPriority, and one solely according to DropsPriority.
> Split channel point farming and drop farming into separate behaviours

- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApi.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/setdropscommunityhighlighttohidden/InputData.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/setdropscommunityhighlighttohidden/SetDropsCommunityHighlightToHiddenData.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/setdropscommunityhighlighttohidden/SetDropsCommunityHighlightToHiddenOperation.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/GQLType.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/SetDropsCommunityHighlightToHiddenPayload.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/UpdateStreamInfo.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/streamer/Streamer.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/streamer/StreamerSettings.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApiSetDropsCommunityHighlightToHiddenTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/runnable/UpdateStreamInfoTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/streamer/PredictionSettingsTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/streamer/StreamerSettingsTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/streamer/StreamerTest.java
- miner/src/test/resources/api/gql/gql/setDropsCommunityHighlightToHidden_success.json
- miner/src/test/resources/config/config-with-more-customization.json
Thanks @jabbink
New Feature
Twitch is now pushing the Apple TV+ "drop" on every channel, which makes drop recognition impossible (available drops highlight service only returns 1 drop, the Apple TV+ one) there's this GQL request to dismiss a drop campaign which I personally call in DropsPriority whenever I run into a sub requirement only drop, or a reward campaign.
> Add setting to dismiss known global ids that hide normal drops

- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/twitch/TwitchApi.java
Bug fix
Apparently twitch now also provides mp4 URLs inside it's m3u8 playlist whereas before there was only ts files. This PR adds the ability to grab mp4 chunks to avoid the error "Failed to get streamer M3U8 chunk from playlist".
> Also grab mp4 chunks from m3u8

- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/DropCampaignSummary.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/UpdateStreamInfo.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApiDropsHighlightServiceAvailableDropsTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/runnable/UpdateStreamInfoTest.java
- miner/src/test/resources/api/gql/gql/dropsHighlightServiceAvailableDrops_withDrops.json
New Feature
Automatically detect Twitch global campaign to dismiss them as soon as they appear
> Automatically detect dismissible site-wide drops campaigns

- miner/docs/modules/ROOT/pages/installation/docker.adoc
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/prediction/bet/amount/ConstantAmount.java
- miner/src/main/resources/log4j2.xml
> Add `LOG_LEVEL` env var to control default miner log level without editing the logger file

- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/pubsub/data/message/BroadcastSettingsUpdate.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/pubsub/data/message/IPubSubMessage.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/pubsub/data/request/topic/TopicName.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/handler/PubSubMessageHandlerAdapter.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/handler/StreamStartEndHandler.java
- miner/src/main/java/fr/rakambda/channelpointsminer/miner/miner/Miner.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/pubsub/TwitchPubSubWebSocketClientMessageTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/handler/StreamStartEndHandlerTest.java
- miner/src/test/java/fr/rakambda/channelpointsminer/miner/miner/MinerTest.java
- miner/src/test/resources/api/ws/broadcastSettingsUpdate.json
New Feature
This event is sent when stream start/stops. However it doesn't send enough info to know if the stream started or ended so we'll have to rely on our internal state which may be unreliable sometimes.
> Listen to `BroadcastSettingsUpdate` message to circumvent missing `streamUp`/`streamDown` events
