.github/workflows/ci.yml
.github/workflows/codeql.yml

Use develop branch

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
README.adoc
src/main/java/fr/raksrinana/channelpointsminer/config/Configuration.java
src/main/java/fr/raksrinana/channelpointsminer/config/StreamerDirectory.java
src/main/java/fr/raksrinana/channelpointsminer/factory/MessageHandlerFactory.java
src/main/java/fr/raksrinana/channelpointsminer/factory/StreamerSettingsFactory.java
src/main/java/fr/raksrinana/channelpointsminer/log/LogLoggerHandler.java
src/main/java/fr/raksrinana/channelpointsminer/miner/Miner.java
src/test/java/fr/raksrinana/channelpointsminer/factory/ConfigurationFactoryTest.java
src/test/java/fr/raksrinana/channelpointsminer/factory/MessageHandlerFactoryTest.java
src/test/java/fr/raksrinana/channelpointsminer/factory/StreamerSettingsFactoryTest.java
src/test/java/fr/raksrinana/channelpointsminer/miner/MinerTest.java
src/test/resources/config/config.json

Allow the definition of several streamer directories with the option to be recursive or not.
Closes #50

Multiple streamer directories

---

README.adoc
src/main/java/fr/raksrinana/channelpointsminer/api/gql/data/types/CommunityPointsCommunityGoalStatus.java
src/main/java/fr/raksrinana/channelpointsminer/prediction/bet/outcome/BiggestPredictorOutcomePicker.java
src/main/java/fr/raksrinana/channelpointsminer/prediction/bet/outcome/OutcomePicker.java
src/test/java/fr/raksrinana/channelpointsminer/prediction/bet/outcome/BiggestPredictorOutcomePickerTest.java

Biggest predictor outcome picker

---

README.adoc
src/main/java/fr/raksrinana/channelpointsminer/prediction/bet/BetPlacer.java
src/main/java/fr/raksrinana/channelpointsminer/prediction/bet/Placement.java
src/main/java/fr/raksrinana/channelpointsminer/prediction/bet/action/PredictionAction.java
src/main/java/fr/raksrinana/channelpointsminer/prediction/bet/action/StealthPredictionAction.java
src/main/java/fr/raksrinana/channelpointsminer/streamer/PredictionSettings.java
src/test/java/fr/raksrinana/channelpointsminer/factory/StreamerSettingsFactoryTest.java
src/test/java/fr/raksrinana/channelpointsminer/prediction/bet/BetPlacerTest.java
src/test/java/fr/raksrinana/channelpointsminer/prediction/bet/action/StealthPredictionActionTest.java
src/test/java/fr/raksrinana/channelpointsminer/streamer/PredictionSettingsTest.java
src/test/resources/factory/fullyOverridden.json

Introduces predictions actions that can perform actions/validations before a bet is placed.
An implementation of this will be the stealth mode ensuring bet amount is lower than the top predictor.
Closes #43

Stealth mode

---

README.adoc
src/main/java/fr/raksrinana/channelpointsminer/runnable/SendMinutesWatched.java
src/main/java/fr/raksrinana/channelpointsminer/streamer/Streamer.java
src/main/java/fr/raksrinana/channelpointsminer/streamer/StreamerSettings.java
src/test/java/fr/raksrinana/channelpointsminer/factory/StreamerSettingsFactoryTest.java
src/test/java/fr/raksrinana/channelpointsminer/runnable/SendMinutesWatchedTest.java
src/test/java/fr/raksrinana/channelpointsminer/streamer/StreamerTest.java
src/test/resources/factory/fullyOverridden.json

Add streamer index to order streamers when they have same score.
Closes #51

Streamer index

---

README.adoc
src/main/java/fr/raksrinana/channelpointsminer/Main.java
src/main/java/fr/raksrinana/channelpointsminer/config/AccountConfiguration.java
src/main/java/fr/raksrinana/channelpointsminer/config/Configuration.java
src/main/java/fr/raksrinana/channelpointsminer/factory/MinerFactory.java
src/main/java/fr/raksrinana/channelpointsminer/factory/StreamerSettingsFactory.java
src/main/java/fr/raksrinana/channelpointsminer/miner/Miner.java
src/test/java/fr/raksrinana/channelpointsminer/factory/ConfigurationFactoryTest.java
src/test/java/fr/raksrinana/channelpointsminer/factory/MinerFactoryTest.java
src/test/java/fr/raksrinana/channelpointsminer/factory/StreamerSettingsFactoryTest.java
src/test/java/fr/raksrinana/channelpointsminer/miner/MinerTest.java
src/test/resources/config/config.json

Add support for multiple account mining.
Closes #47

Multi accounts

---

README.adoc
build.gradle.kts
src/main/java/fr/raksrinana/channelpointsminer/api/discord/data/Author.java
src/main/java/fr/raksrinana/channelpointsminer/api/discord/data/Embed.java
src/main/java/fr/raksrinana/channelpointsminer/api/discord/data/Field.java
src/main/java/fr/raksrinana/channelpointsminer/api/discord/data/Footer.java
src/main/java/fr/raksrinana/channelpointsminer/api/discord/data/Image.java
src/main/java/fr/raksrinana/channelpointsminer/api/discord/data/Webhook.java
src/main/java/fr/raksrinana/channelpointsminer/config/AccountConfiguration.java
src/main/java/fr/raksrinana/channelpointsminer/config/DiscordConfiguration.java
src/main/java/fr/raksrinana/channelpointsminer/factory/MessageHandlerFactory.java
src/main/java/fr/raksrinana/channelpointsminer/factory/MinerFactory.java
src/main/java/fr/raksrinana/channelpointsminer/log/DiscordLoggerHandler.java
src/main/java/fr/raksrinana/channelpointsminer/miner/Miner.java
src/test/java/fr/raksrinana/channelpointsminer/factory/ConfigurationFactoryTest.java
src/test/java/fr/raksrinana/channelpointsminer/factory/MessageHandlerFactoryTest.java
src/test/java/fr/raksrinana/channelpointsminer/factory/MinerFactoryTest.java
src/test/java/fr/raksrinana/channelpointsminer/log/DiscordLoggerHandlerEmbedTest.java
src/test/java/fr/raksrinana/channelpointsminer/log/DiscordLoggerHandlerMessageTest.java
src/test/java/fr/raksrinana/channelpointsminer/log/DiscordLoggerHandlerTest.java
src/test/java/fr/raksrinana/channelpointsminer/miner/MinerTest.java
src/test/resources/config/config.json

* Embeds colors per type instead of per message
* Allow to disable embeds and send messages instead

Improve discord messages

---

README.adoc
src/main/java/fr/raksrinana/channelpointsminer/handler/ClaimAvailableHandler.java
src/main/java/fr/raksrinana/channelpointsminer/handler/FollowRaidHandler.java
src/main/java/fr/raksrinana/channelpointsminer/handler/PredictionsHandler.java
src/main/java/fr/raksrinana/channelpointsminer/handler/StreamStartEndHandler.java
src/main/java/fr/raksrinana/channelpointsminer/irc/TwitchIrcClient.java
src/main/java/fr/raksrinana/channelpointsminer/irc/TwitchIrcEventListener.java
src/main/java/fr/raksrinana/channelpointsminer/irc/TwitchIrcFactory.java
src/main/java/fr/raksrinana/channelpointsminer/log/DiscordLoggerHandler.java
src/main/java/fr/raksrinana/channelpointsminer/log/LogContext.java
src/main/java/fr/raksrinana/channelpointsminer/log/LogLoggerHandler.java
src/main/java/fr/raksrinana/channelpointsminer/miner/IMiner.java
src/main/java/fr/raksrinana/channelpointsminer/miner/Miner.java
src/main/java/fr/raksrinana/channelpointsminer/prediction/bet/BetPlacer.java
src/main/java/fr/raksrinana/channelpointsminer/runnable/SendMinutesWatched.java
src/main/java/fr/raksrinana/channelpointsminer/runnable/StreamerConfigurationReload.java
src/main/java/fr/raksrinana/channelpointsminer/runnable/SyncInventory.java
src/main/java/fr/raksrinana/channelpointsminer/runnable/UpdateStreamInfo.java
src/main/java/fr/raksrinana/channelpointsminer/runnable/WebSocketPing.java
src/main/java/fr/raksrinana/channelpointsminer/streamer/Streamer.java
src/test/java/fr/raksrinana/channelpointsminer/irc/TwitchIrcClientTest.java
src/test/java/fr/raksrinana/channelpointsminer/irc/TwitchIrcEventListenerTest.java
src/test/java/fr/raksrinana/channelpointsminer/irc/TwitchIrcFactoryTest.java
src/test/java/fr/raksrinana/channelpointsminer/log/DiscordLoggerHandlerEmbedTest.java
src/test/java/fr/raksrinana/channelpointsminer/log/DiscordLoggerHandlerMessageTest.java
src/test/java/fr/raksrinana/channelpointsminer/miner/MinerTest.java

Improve logs to include account used to do the mining

---

src/main/java/fr/raksrinana/channelpointsminer/handler/PredictionsHandler.java
src/test/java/fr/raksrinana/channelpointsminer/api/ws/TwitchWebSocketClientMessageTest.java
src/test/java/fr/raksrinana/channelpointsminer/api/ws/TwitchWebSocketClientPongTest.java
src/test/java/fr/raksrinana/channelpointsminer/api/ws/TwitchWebSocketClientResponseTest.java
src/test/java/fr/raksrinana/channelpointsminer/api/ws/TwitchWebSocketClientTest.java
src/test/java/fr/raksrinana/channelpointsminer/handler/PredictionsHandlerEventUpdatedTest.java
src/test/java/fr/raksrinana/channelpointsminer/tests/WebsocketMockServer.java

Place prediction from event update event

---

.github/release.yml
src/main/java/fr/raksrinana/channelpointsminer/log/event/AbstractLogEvent.java
src/test/java/fr/raksrinana/channelpointsminer/log/event/AbstractLogEventTest.java

Fix millify format

---

src/main/java/fr/raksrinana/channelpointsminer/log/event/AbstractLogEvent.java
src/main/java/fr/raksrinana/channelpointsminer/log/event/AbstractStreamerLogEvent.java
src/main/java/fr/raksrinana/channelpointsminer/log/event/ClaimAvailableLogEvent.java
src/main/java/fr/raksrinana/channelpointsminer/log/event/DropClaimLogEvent.java
src/main/java/fr/raksrinana/channelpointsminer/log/event/EventCreatedLogEvent.java
src/main/java/fr/raksrinana/channelpointsminer/log/event/MinerStartedLogEvent.java
src/main/java/fr/raksrinana/channelpointsminer/log/event/PointsEarnedLogEvent.java
src/main/java/fr/raksrinana/channelpointsminer/log/event/PointsSpentLogEvent.java
src/main/java/fr/raksrinana/channelpointsminer/log/event/PredictionMadeLogEvent.java
src/main/java/fr/raksrinana/channelpointsminer/log/event/PredictionResultLogEvent.java
src/main/java/fr/raksrinana/channelpointsminer/log/event/StreamDownLogEvent.java
src/main/java/fr/raksrinana/channelpointsminer/log/event/StreamUpLogEvent.java
src/main/java/fr/raksrinana/channelpointsminer/log/event/StreamerAddedLogEvent.java
src/main/java/fr/raksrinana/channelpointsminer/log/event/StreamerRemovedLogEvent.java
src/main/java/fr/raksrinana/channelpointsminer/log/event/StreamerUnknownLogEvent.java
src/main/java/fr/raksrinana/channelpointsminer/runnable/SyncInventory.java
src/test/java/fr/raksrinana/channelpointsminer/log/DiscordLogEventListenerEmbedTest.java
src/test/java/fr/raksrinana/channelpointsminer/log/DiscordLogEventListenerMessageTest.java
src/test/java/fr/raksrinana/channelpointsminer/log/event/AbstractLogEventTest.java
src/test/java/fr/raksrinana/channelpointsminer/runnable/SyncInventoryTest.java

Claim drop log

---

src/main/java/fr/raksrinana/channelpointsminer/factory/ConfigurationFactory.java

Display config path when failed to open it

---

src/main/java/fr/raksrinana/channelpointsminer/util/CommonUtils.java

…is present for 2FA
Closes #89

Display warning about docker and interactive mode when no user input is present for 2FA

---

README.adoc
src/main/java/fr/raksrinana/channelpointsminer/factory/StreamerSettingsFactory.java
src/test/java/fr/raksrinana/channelpointsminer/factory/StreamerSettingsFactoryTest.java

Parse empty streamer files as default settings

---

build.gradle.kts

Add arm/v7 as docker platform & switch to temurin as base image

---

src/main/java/fr/raksrinana/channelpointsminer/api/gql/data/types/CommunityPointsCommunityGoalStatus.java

Add STARTED as CommunityPointsCommunityGoalStatus value

---

.github/workflows/ci.yml
src/main/java/fr/raksrinana/channelpointsminer/api/ws/data/message/IMessage.java
src/main/java/fr/raksrinana/channelpointsminer/api/ws/data/message/RaidCancelV2.java
src/test/java/fr/raksrinana/channelpointsminer/api/ws/TwitchWebSocketClientMessageTest.java
src/test/resources/api/ws/raidCancelV2.json

Handle RaidCancelV2 ws event

---

src/main/java/fr/raksrinana/channelpointsminer/handler/StreamStartEndHandler.java
src/main/java/fr/raksrinana/channelpointsminer/miner/IMiner.java
src/main/java/fr/raksrinana/channelpointsminer/miner/Miner.java
src/test/java/fr/raksrinana/channelpointsminer/handler/StreamStartEndHandlerTest.java
src/test/java/fr/raksrinana/channelpointsminer/miner/MinerTest.java

Join IRC only when user is streaming

---

src/main/java/fr/raksrinana/channelpointsminer/util/json/URLDeserializer.java
src/test/java/fr/raksrinana/channelpointsminer/util/json/URLDeserializerTest.java

If URL has no scheme, assume it is https

---

src/main/java/fr/raksrinana/channelpointsminer/api/ws/TwitchWebSocketClient.java
src/main/java/fr/raksrinana/channelpointsminer/api/ws/data/response/ITwitchWebSocketResponse.java
src/main/java/fr/raksrinana/channelpointsminer/api/ws/data/response/ReconnectResponse.java
src/test/java/fr/raksrinana/channelpointsminer/api/ws/TwitchWebSocketClientReconnectTest.java
src/test/resources/api/ws/reconnect.json

Reconnect WS when notified it'll disappear

---

README.adoc
src/main/java/fr/raksrinana/channelpointsminer/prediction/bet/amount/KellyAmount.java
src/main/java/fr/raksrinana/channelpointsminer/prediction/bet/outcome/KellyOutcomePicker.java
src/test/java/fr/raksrinana/channelpointsminer/prediction/bet/amount/KellyAmountTest.java
src/test/java/fr/raksrinana/channelpointsminer/prediction/bet/outcome/KellyOutcomePickerTest.java

Add kelly betting

---

gradle.properties
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/createnotification/Notification.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/createnotification/NotificationRenderStyle.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/ws/TwitchWebSocketClientMessageTest.java

Fix notification message not being able to be parsed

---

gradle.properties
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/createnotification/Notification.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/createnotification/NotificationRenderStyle.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/ws/TwitchWebSocketClientMessageTest.java

Reverts RakSrinaNa/ChannelPointsMiner#187

Revert "Fix notification message not being able to be parsed"

---

miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/createnotification/Notification.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/createnotification/NotificationRenderStyle.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/ws/TwitchWebSocketClientMessageTest.java

Fix notification render style not being able to be parsed

---

README.adoc
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLApi.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/data/chatroombanstatus/ChatRoomBanStatusData.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/data/chatroombanstatus/ChatRoomBanStatusOperation.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/data/types/ChatRoomBanStatus.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/data/types/GQLType.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/runnable/SendMinutesWatched.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/runnable/UpdateStreamInfo.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/streamer/Streamer.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/GQLApiChatRoomBanStatusTest.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/runnable/SendMinutesWatchedTest.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/runnable/UpdateStreamInfoTest.java
miner/src/test/resources/api/gql/channelRoomBanStatus_banned.json
miner/src/test/resources/api/gql/channelRoomBanStatus_notBanned.json

Skip banned channels

---

miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/TwitchWebSocketClient.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/IMessage.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/WatchPartyVod.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/watchpartyvod/Vod.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/ws/TwitchWebSocketClientMessageTest.java
miner/src/test/resources/api/ws/watchPartyVod.json

Parse WatchPartyVOD message

---

miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/passport/PassportApi.java

Display username when asking 2FA

---

miner/src/main/java/fr/raksrinana/channelpointsminer/miner/streamer/StreamerSettings.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/factory/StreamerSettingsFactoryTest.java
miner/src/test/resources/factory/partiallyOverridden.json

Improve settings overriding for predictions

---

gradle/libs.versions.toml
miner/build.gradle.kts
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/database/BaseDatabase.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/database/MariaDBDatabase.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/database/SQLiteDatabase.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/factory/DatabaseFactory.java
miner/src/main/resources/db/migrations/mariadb/V1_0_0__base.sql
miner/src/main/resources/db/migrations/sqlite/V1_0_0__base.sql

Will ease future DB migrations

Add Flyway to ease future DB migrations

---

miner/src/main/java/fr/raksrinana/channelpointsminer/miner/database/DatabaseEventHandler.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/database/DatabaseEventHandlerTest.java

Handle case where winning outcome had no betters

---

miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/communitymoment/CommunityMomentStartData.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/handler/ClaimMomentHandler.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/ws/TwitchPubSubWebSocketClientMessageTest.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/handler/ClaimMomentHandlerTest.java
miner/src/test/resources/api/ws/communityMomentStart.json

Updates on moments claiming

---

miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/ActiveMultipliersUpdated.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/IPubSubMessage.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/activemultipliersupdated/ActiveMultipliersUpdatedData.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/subtype/ActiveMultipliers.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/ws/TwitchPubSubWebSocketClientMessageTest.java
miner/src/test/resources/api/ws/activeMultipliersUpdated.json

Parse active multiplier updated event

---

miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/subtype/NotificationDisplayType.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/subtype/NotificationSummary.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/subtype/NotificationSummaryByDisplayType.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/subtype/Summary.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/ws/TwitchPubSubWebSocketClientMessageTest.java
miner/src/test/resources/api/ws/updateSummary.json

Fix unknown field 'summaries_by_display_type' in update-summary

---

README.adoc
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/integrity/IntegrityException.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/integrity/http/HttpIntegrityProvider.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/version/IVersionProvider.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/version/VersionException.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/version/manifest/ManifestVersionProvider.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/version/manifest/data/ManifestChannel.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/version/manifest/data/ManifestRelease.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/version/manifest/data/ManifestResponse.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/version/webpage/WebpageVersionProvider.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/config/AccountConfiguration.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/config/VersionProvider.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/factory/ApiFactory.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/miner/Miner.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/integrity/http/HttpIntegrityProviderTest.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/version/manifest/ManifestVersionProviderTest.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/version/webpage/WebpageVersionProviderTest.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/factory/ApiFactoryTest.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/factory/ConfigurationFactoryTest.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/miner/MinerTest.java
miner/src/test/resources/api/gql/version/manifest.json
miner/src/test/resources/config/config-with-more-customization.json

Add VersionProvider to choose how to obtain twitch version

---

miner/docs/modules/ROOT/examples/global-config-schema.json
miner/docs/modules/ROOT/examples/streamer-config-schema.json
miner/docs/modules/ROOT/pages/configuration/global.adoc
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/integrity/http/MobileIntegrityProvider.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/passport/TwitchClient.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/passport/TwitchLogin.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/passport/browser/BrowserPassportApi.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/passport/http/HttpPassportApi.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/passport/http/data/LoginRequest.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/config/login/ILoginMethod.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/config/login/IPassportApiLoginProvider.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/config/login/MobileLoginMethod.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/factory/ApiFactory.java
miner/src/schema/java/fr/raksrinana/channelpointsminer/miner/ConfigSchemaGenerator.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/chat/ws/TwitchChatWebSocketClientTest.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/integrity/http/MobileIntegrityProviderTest.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/passport/TwitchLoginTest.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/passport/browser/BrowserPassportApiTest.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/passport/http/HttpPassportApiTest.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/factory/ApiFactoryTest.java
miner/src/test/resources/api/passport/expectedAuth.json
miner/src/test/resources/api/passport/mobileAuth.json

New Feature
Add a new `MOBILE` login method that uses a different ClientID (android mobile app). 
This means integrity checks are working without issue and does not require a selenium instance (just your user/password/2fa).
This is a nice alternative for those not wanting to use a selenium instance but is maybe more prone to be detected by twitch as lots of values are hardcoded.
Old authentication files will be invalidated. You'll have to deleted them and log in again (or log with the `BROWSER` method that should work)

Add new MOBILE login method

---

miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/twitch/TwitchApi.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/runnable/UpdateStreamInfo.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/twitch/TwitchApiTest.java

Fix Spade url sometimes not being found

---

miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/gql/data/types/MakePredictionErrorCode.java

Fix parsing prediction error code

---

miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/createnotification/CreateNotificationData.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/createnotification/ImageBlock.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/createnotification/ImageContent.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/createnotification/ImageNotificationDataBlock.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/createnotification/Notification.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/createnotification/NotificationDataBlock.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/createnotification/TextBlock.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/createnotification/TextContent.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/ws/data/message/createnotification/TextNotificationDataBlock.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/ws/TwitchPubSubWebSocketClientMessageTest.java
miner/src/test/resources/api/ws/createNotification2.json

Parse new create notification format

---

miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/gql/GQLApi.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/api/gql/integrity/http/MobileIntegrityProvider.java
miner/src/main/java/fr/raksrinana/channelpointsminer/miner/factory/ApiFactory.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/gql/AbstractGQLTest.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/api/gql/integrity/http/MobileIntegrityProviderTest.java
miner/src/test/java/fr/raksrinana/channelpointsminer/miner/factory/ApiFactoryTest.java

Fix mobile auth

---

.gitignore
miner/docs/modules/ROOT/examples/global-config-schema.json
miner/docs/modules/ROOT/examples/streamer-config-schema.json
miner/docs/modules/ROOT/pages/configuration/global.adoc
miner/src/main/java/fr/rakambda/channelpointsminer/miner/config/login/MobileLoginMethod.java
miner/src/main/java/fr/rakambda/channelpointsminer/miner/factory/ApiFactory.java
miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/gql/integrity/http/MobileIntegrityProviderTest.java
miner/src/test/java/fr/rakambda/channelpointsminer/miner/factory/ApiFactoryTest.java

Mobile auth is back

---

miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/MakePredictionErrorCode.java

Add EVENT_NOT_ACTIVE to prediction error codes

---

miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/ClaimErrorCode.java

Fix parsing FORBIDDEN as claiming event error code

---

gradle/libs.versions.toml
miner/build.gradle.kts
miner/docs/modules/ROOT/pages/configuration/global.adoc
miner/src/main/java/fr/rakambda/channelpointsminer/miner/config/DatabaseConfiguration.java
miner/src/main/java/fr/rakambda/channelpointsminer/miner/database/MysqlDatabase.java
miner/src/main/java/fr/rakambda/channelpointsminer/miner/factory/DatabaseFactory.java
miner/src/main/resources/db/migrations/mysql/V1_0_0__base.sql

Add MySQL support for analytics database

---

miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/dropshighlightserviceavailabledrops/DropsHighlightServiceAvailableDropsOperation.java
miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApiDropsHighlightServiceAvailableDropsTest.java

fix: DropsHighlightService_AvailableDrops gql request changed

---

.github/workflows/build-test-deploy.yml
.github/workflows/release.yml

Add built jar to CI jobs (14 days) & to releases

---

miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/inventory/InventoryOperation.java
miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/Inventory.java
miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApiInventoryTest.java

New GQL requests for Inventory

---

miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/dropspageclaimdroprewards/DropsPageClaimDropRewardsOperation.java
miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApiDropsPageClaimDropRewardsTest.java

Fix DropsPage_ClaimDropRewards query

---

miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/ClaimDropRewardsPayload.java

Fix parsing `dropType` in ClaimDropRewardsPayload

---

.gitignore
miner/src/main/java/fr/rakambda/channelpointsminer/miner/factory/StreamerSettingsFactory.java
miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/StreamerConfigurationReload.java
miner/src/test/java/fr/rakambda/channelpointsminer/miner/runnable/StreamerConfigurationReloadInitialNoFollowsTest.java

Bug fix
Having several files for the same streamer (ie: in different folders) hangs the loading of the streamers.

Fixed several json file for same streamer hanging loading

---

miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/dropshighlightserviceavailabledrops/DropsHighlightServiceAvailableDropsData.java
miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/dropshighlightserviceavailabledrops/DropsHighlightServiceAvailableDropsOperation.java
miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApiDropsHighlightServiceAvailableDropsTest.java
miner/src/test/resources/api/gql/gql/dropsHighlightServiceAvailableDrops_noDrops.json
miner/src/test/resources/api/gql/gql/dropsHighlightServiceAvailableDrops_withDrops.json

Internal change
Previous hash seems to still be working. Using new one to be aligned with Twitch practices.

Update DropsHighlightService_AvailableDrops hash

---

miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/MakePredictionErrorCode.java

Add new prediction result : RATE_LIMITED

---

.github/workflows/build-test-deploy.yml

Reverts Rakambda/ChannelPointsMiner#584

Revert "chore(deps): update codecov/codecov-action action to v4"

---

miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/ContentId.java

Add new content id SEND_ANIMATED_MESSAGE

---

miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/twitch/TwitchApi.java
miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/twitch/TwitchApiTest.java

Fix spade_url not found

---

miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendM3u8MinutesWatched.java
miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendMinutesWatched.java
miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendSpadeMinutesWatched.java
miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/UpdateStreamInfo.java
miner/src/test/java/fr/rakambda/channelpointsminer/miner/runnable/UpdateStreamInfoTest.java

Do not make m3u8 requests if streamer does not activate drops

---

miner/src/main/java/fr/rakambda/channelpointsminer/miner/factory/MinerFactory.java
miner/src/main/java/fr/rakambda/channelpointsminer/miner/factory/PubSubMessageHandlerFactory.java
miner/src/test/java/fr/rakambda/channelpointsminer/miner/factory/MinerFactoryTest.java
miner/src/test/java/fr/rakambda/channelpointsminer/miner/factory/PubSubMessageHandlerFactoryTest.java

A notification handler was created to listen notifications and claim drops. However it was never initialized and added to the ;iner. This PR fixes that.

Actually listen to notifications to claim drops

---

miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/dropshighlightserviceavailabledrops/DropsHighlightServiceAvailableDropsOperation.java
miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApiDropsHighlightServiceAvailableDropsTest.java

Use new operation id for DropsHighlightService_AvailableDrops

---

.github/ISSUE_TEMPLATE/0_bug_report.yml
.github/ISSUE_TEMPLATE/1_feature_request.yml
miner/build.gradle.kts

Bug fix
See https://logging.staged.apache.org/log4j/2.x/faq.html#single-jar

Fix log4j2 error when launching app from shaded jar

---

.github/workflows/release.yml

Reverts RakambdaOrg/ChannelPointsMiner#947

Revert "chore(deps): update softprops/action-gh-release action to v2.2.0"

---

miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/playbackaccesstoken/PlaybackAccessTokenOperation.java
miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApiPlaybackAccessTokenTest.java

Update PlaybackAccessToken GQL request with new signature
